[package]
name = "moonbeam-finality-rpc"
authors = [ "PureStake" ]
description = "An experimental RPC to check for block and transaction finality in the moonbeam parachain"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.1.0"

[dependencies]
futures = { version = "0.3", features = [ "compat" ] }
jsonrpsee = { version = "0.14.0", default-features = false, features = [ "macros", "server" ] }
parity-scale-codec = "3.0.0"
tokio = { version = "1.12.0", features = [ "sync", "time" ] }

fc-db = { git = "https://github.com/zeitgeistpm/frontier", branch = "polkadot-v0.9.26-libp2p" }
fc-rpc = { git = "https://github.com/zeitgeistpm/frontier", branch = "polkadot-v0.9.26-libp2p" }
sp-api = { git = "https://github.com/zeitgeistpm/substrate", branch = "polkadot-v0.9.26-libp2p" }
sp-blockchain = { git = "https://github.com/zeitgeistpm/substrate", branch = "polkadot-v0.9.26-libp2p" }
sp-core = { git = "https://github.com/zeitgeistpm/substrate", branch = "polkadot-v0.9.26-libp2p" }
sp-runtime = { git = "https://github.com/zeitgeistpm/substrate", branch = "polkadot-v0.9.26-libp2p" }
